### ISSUE TITLE
segfault when built with extra hardening flags

### ISSUE THREAD

**Issue by LnL7** [koekeishiya/skhd#28] opened 2018-03-03 12:09 UTC
```
skhd: using config '/etc/skhdrc'
(#2) hotkey :: {
        mod: 'cmd'
        key: 'return' (0x24)
        cmd: 'open -na /Applications/Kitty.app'
}
(#5) hotkey :: {
        mod: 'alt'
Abort trap: 6
```

These are the extra extra flags that get added by the hardening. Initially I thought this was this the extra -O flag, but disabling the fortify flags isn't enough.

```diff
@@ -1,5 +1,11 @@
-clang src/skhd.c -std=c99 -O3 -framework Carbon -o /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-skhd-0.0.10/bin/skhd
+clang src/skhd.c -std=c99 -O3 -framework Carbon -o /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-skhd-0.0.10/bin/skhd
+HARDENING: enabling fortify
+HARDENING: enabling stackprotector
+HARDENING: enabling pic
+HARDENING: enabling strictoverflow
+HARDENING: enabling format
 extra flags before to /nix/store/insiq14mv3l2lsb90d8671qqda9i75d4-clang-5.0.1/bin/clang:
   ''
 original flags to /nix/store/insiq14mv3l2lsb90d8671qqda9i75d4-clang-5.0.1/bin/clang:
@@ -9,7 +15,7 @@
   -framework
   Carbon
   -o
-  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-skhd-0.0.10/bin/skhd
+  /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-skhd-0.0.10/bin/skhd
 extra flags after to /nix/store/insiq14mv3l2lsb90d8671qqda9i75d4-clang-5.0.1/bin/clang:
   -B/nix/store/6r5bk2qiq7m6n1fr7khf7p1xz26l2lqy-clang-5.0.1-lib/lib
   -B/nix/store/lvbg3qxa84bck05k425mj5n4hxx2n60n-Libsystem-osx-10.11.6/lib/
@@ -88,6 +94,16 @@
   -F/nix/store/illzh78sjn4g607ad5ikyhyq3snp5jhq-apple-framework-OpenGL/Library/Frameworks
   -F/nix/store/6ixzazaqm0pw364fzl0r4dvbaj55z49x-apple-framework-OpenCL/Library/Frameworks
   -F/nix/store/g94jv2hb0sadznj8dy39vxdvp6cj35z5-CF-osx-10.10.5/Library/Frameworks
+  -O2
+  -D_FORTIFY_SOURCE=2
+  -fstack-protector-strong
+  --param
+  ssp-buffer-size=4
+  -fPIC
+  -fno-strict-overflow
+  -Wformat
+  -Wformat-security
+  -Werror=format-security
   -L/nix/store/j6ifwrr83k1c5nmjfx1p63nydpqsbqd6-libc++-5.0.1/lib
   -L/nix/store/r5vgpicc9m7niyjxa0rc30raxyd58dsl-objc4-osx-10.11.6/lib
   -L/nix/store/j6ifwrr83k1c5nmjfx1p63nydpqsbqd6-libc++-5.0.1/lib
```

/cc @peel

**Comment by koekeishiya** [comment] 2018-03-22 21:09
I have no idea why that segfault is happening. I don't see any errors in the code, and I'm not able to reproduce this on my machine in either optimized or debug builds, making it very hard to identify where the problem is coming from. 

I get no warnings when compiling with -Wall either.

**Comment by koekeishiya** [comment] 2018-03-24 20:18
So the crash is happening when i *step* over the following line: https://github.com/koekeishiya/skhd/blob/df3d13c9e655c5a566d471256b5e54cca796f576/src/locale.c#L70

The code runs fine and the keycode gets the proper value, but it crashes upon returning from the function.

**Comment by koekeishiya** [comment] 2018-03-24 20:47
Fixed on master. Thanks for the detailed report.

**Closed** 2018-03-24 20:46 UTC
Labels: bug

**Comment by LnL7** [comment] 2018-03-24 21:52
Great! I'm not sure if it's related to this change, but with the latest version all key mappings seem to get translated to `a`. For example:


```sh
alt - x : echo x  # ignored
alt - y : echo y  # alt - a
alt + shift - x : echo X  # ignored
alt + shift - y : echo Y  # alt + shfit - a
```

**Comment by koekeishiya** [comment] 2018-03-24 22:40
nah definitely the one that fixed the segfault...gah

**Comment by koekeishiya** [comment] 2018-03-24 22:59
Gonna get rid of the stupid CFDictionary way of caching i guess..

**Comment by koekeishiya** [comment] 2018-03-24 23:39
ok now, fixed on master <.<

**Comment by LnL7** [comment] 2018-03-24 23:54
That looks better, 😄 Thanks!
