### ISSUE TITLE
Blocking native MacOS screen capture application

### ISSUE THREAD

**Issue by adam-erickson** [koekeishiya/skhd#66] opened 2019-03-05 03:18 UTC
It appears that `skhd` is blocking the native screen capture application (the hotkey variants) on MacOS. The Grab application still works fine. Stopping the `skhd` brew service fixes the issue.

**Comment by dominiklohmann** [comment] 2019-03-05 07:01
Duplicate of #64.

**Comment by koekeishiya** [comment] 2019-03-05 16:43
Closing this, see issue referenced by @dominiklohmann

**Closed by koekeishiya** 2019-03-05 16:43 UTC
