### ISSUE TITLE
some keymaps ignore modifiers

### ISSUE THREAD

**Issue by Alok** [koekeishiya/skhd#12] opened 2017-10-01 21:21 UTC
I have the mapping `shift + ctrl - t : chunkc tiling::window --swap west`.

However, with the HEAD build of skhd using Homebrew, pressing the `t` key by itself causes the mapping to execute, which makes the key worthless.

**Comment by koekeishiya** [comment] 2017-10-02 10:20
Does this happen if you clone the repo and build from source, instead of using brew.
I don't trust the optimization level specified by brew.. See #7 for example of this..

**Comment by koekeishiya** [comment] 2017-10-02 15:03
I'm unable to reproduce this on my end. Can you try installing the latest version?
If the issue persist with the brew installation, can you also try to build manually from source.
Thanks.

**Comment by koekeishiya** [comment] 2017-11-22 14:46
Closing this as I still can't reproduce. Feel free to reopoen or create a new issue if you can provide steps to reproduce the problem.

**Closed by koekeishiya** 2017-11-22 14:46 UTC
