### ISSUE TITLE
skhd not working properly when run with "brew services", but works fine when run from shell

### ISSUE THREAD

**Issue by tobiasstier** [koekeishiya/skhd#103] opened 2019-11-26 11:28 UTC
When using `brew services start --all` to start both skhd and yabai, my keybind for creating a desktop and changing focus doesn't work:

`alt + cmd - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                  yabai -m space --focus "${index}"
`

However, if I simply just run skhd from the terminal, it works fine. This is both with yabai being run as service and as a shell process, leading me to believe it is a problem with skhd. skhd is installed with homebrew and using the `--HEAD` argument, as my skhdrc is in ~/.config/skhd.

Any help much appreciated :) 

EDIT:
I'm starting to think it may be a problem with the yabai scripting addition, as when I use `sudo yabai --load-sa`, it returns 
`yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -10004`. Is this a correct assumption?

**Comment by camspiers** [comment] 2019-12-26 07:19
I'm experiencing this too, it appears to be related to `skhd` failing to load config files specifically from `.config/skhd/skhdrc` when running `brew services start skhd` but not when running `skhd` by itself. I fixed this issue by adding a symlink to `~/.skhdrc` but I would rather not have to do this.

@koekeishiya this appear to reproduce fairly easily.

**Comment by frayment** [comment] 2019-12-29 00:20
I can confirm this is indeed the case. I am receiving the same problem with the same reproducibility.

**Comment by frayment** [comment] 2020-01-01 19:24
So I've been doing some digging around and I'm fairly certain this is happening because brew is still using the latest release (0.3.4) which was released in May, long before commit `faff8543ffc01d3a6c017a187761c17d76afc3fa` in September which significantly changed the way the config files are found.

@koekeishiya Can we please get a new release for brew?

**Comment by koekeishiya** [comment] 2020-01-18 13:33
v0.3.5 is now on brew.

**Closed by koekeishiya** 2020-01-18 13:33 UTC

**Comment by cormacrelf** [comment] 2020-02-21 10:08
FWIW I am still kinda experiencing this with 0.3.5. I had `~/.skhdrc` symlinked to my dotfiles, and when running under launchd, this wasn't being read (or wasn't being followed, not sure). Running directly I could not observe the issue. I've worked around it by moving the actual file to `~/.config/skhd/skhdrc`, but this is less than ideal.

**Comment by aSapien** [comment] 2021-01-12 11:47
Same issue here after upgrading to Big Sur, running `v0.3.5`

**Comment by armand1m** [comment] 2021-01-16 22:09
I'm also having the same issue in Big Sur right now;

Running `yabai -m space --focus 2` if there is a Desktop 2 returns exit code 0 but does nothing

**Comment by DxTa** [comment] 2021-02-11 08:58
I managed to make it word in Big Sur following these steps:
1. uninstall both yabai and skhd
2. install yabai and skhd again
3. run `sudo yabai --uninstall-sa && sudo yabai --install-sa && sudo yabai --load-sa` to load sa again after first yabai installation

**Comment by gronk-droid** [comment] 2022-02-09 19:30
did anyone ever find a solution to this? even with a symlink from `~/.skhdrc` to `~/.config/skhd/skhdrc` I am still having a problem getting the daemon to read my configs. as @aSapien stated in [issue 139](https://github.com/koekeishiya/skhd/issues/139):
> I don't like this solution much because it might leave the `skhd` process alive after `yabai` terminates, but it's something.

**Comment by gronk-droid** [comment] 2022-02-09 21:24
scratch that—look at my reply in [issue #139](https://github.com/koekeishiya/skhd/issues/139)
