### ISSUE TITLE
Hotkey using [ cmd + num ] not detected

### ISSUE THREAD

**Issue by matthiasbe** [koekeishiya/skhd#75] opened 2019-04-09 07:24 UTC
Hi,
First of all thanks for these awesome projects, I'm a linux fan using an osx at work, I was really looking for a tiling wm 👍 

There is something odd with my installation of skhd + chunkwm though, hotkeys `[cmd - 1]`, `[ctrl + cmd - 1]`, and more generally something like `[ cmd | ctrl | alt | shift + [ 1 - 9 ] ]` is not detected.

I have also tried with `&` instead of `1`, `é` instead of `2` etc ...  without any success.
My keyboard looks like this
![keyboard photo](https://www.macway.com/images/p/g/originalid_94000/300/94343/zoom/94343_8906cb4.jpg)

I'm on Mojave 10.14.4
I'm using latest HEAD but this didn't work either with the homebrew current build.

Oh it seems it's related to https://github.com/koekeishiya/skhd/issues/30 

If you would like more information please tell me 😉

**Comment by matthiasbe** [comment] 2019-04-10 11:44
Replacing `cmd + 1`with `cmd + 0x12`works like a charm, thank you 👍 

If you want some info about the cause of the aliasing gap, feel free to ask

**Comment by koekeishiya** [comment] 2019-04-10 12:26
Glad the keycode trick worked. I'll take another look at how the keycode mapping table is generated.

> PS : I couldn't get cevto work, I had the message cev: could not create event-tap, try running as root!even if I started the program with sudo cev. Do you want me to post an issue on the appropriate repo ?

Not necessary. I plan to add support for this to *skhd* itself at some point before the next release.

**Comment by koekeishiya** [comment] 2019-04-13 17:11
Added support for observing keyevents and outputting keycode/modifier information.
Launch as: `skhd --observe` or `skhd -o`. Press `ctrl+c` to quit.

**Comment by koekeishiya** [comment] 2020-01-18 13:35
I actually cannot reproduce this. Closing for now. If someone else experiences the same behaviour we can create a new issue for that.

**Closed by koekeishiya** 2020-01-18 13:35 UTC
