### ISSUE TITLE
bind single key in mode

### ISSUE THREAD

**Issue by theonlygusti** [koekeishiya/skhd#82] opened 2019-05-21 10:50 UTC
I want to type keypress sequences, like cmd - o then l to go to the right window

I tried

```
cmd - o ; command

command < l : chunkc tiling::window --focus east ; default
```

thinking cmd - o puts into command mode, and in command mode, l goes to the right window and puts back into default mode

but it didn't work

**Comment by dominiklohmann** [comment] 2019-05-21 10:57
There are two misunderstandings at play here:

You need to define the mode first. Second, everything that comes after the colon in a command gets passed to your `$SHELL`, which means that the semicolon does not mean "enter mode" here. Instead, define a separate command that actives the default mode and invoke it from your other command.

```
# register mode "command"
:: command

# when in default mode, cmd - o activates command mode
cmd - o ; command

# when in command mode, cmd - o activates default mode
command < cmd - o ; default

# when in command mode, pressing l executes focus east command, then presses cmd - o
command < l : chunkc tiling::window --focus east ; skhd --key "cmd - o"
```

**Comment by theonlygusti** [comment] 2019-05-21 11:55
@dominiklohmann it still doesn't work, and I literally copy/pasted what you put

**Comment by dominiklohmann** [comment] 2019-05-21 12:11
The exact code block does what you described in your initial post on my end. 

I recommend reading this guide on [asking smart questions](http://www.catb.org/~esr/faqs/smart-questions.html), especially the part about [being precise](http://www.catb.org/~esr/faqs/smart-questions.html#beprecise). This is not meant as smartassery, but saying "it does not work" will not get you any further.

**Comment by theonlygusti** [comment] 2019-05-21 12:48
@dominiklohmann my `~/.skhdrc` is literally just

```
:: command

cmd - o ; command
command < cmd - o ; default

command < cmd - h : chunkc tiling::window --focus west ; skhd --key 'cmd - o'
command < cmd - j : chunkc tiling::window --focus south ; skhd --key 'cmd - o'
command < cmd - k : chunkc tiling::window --focus north ; skhd --key 'cmd - o'
command < cmd - l : chunkc tiling::window --focus east ; skhd --key 'cmd - o'
```

But after pressing cmd - o all the cmd -h etc. key binds are just sent like normal through to the app I'm in

**Comment by koekeishiya** [comment] 2019-05-21 12:55
Secure Keyboard Entry is likely enabled by some application. I’d link you to information to verify if I wasnt on my phone, but you can search the issues to find the relevant information.

Sent from my iPhone

On 21 May 2019, at 14:48, George <notifications@github.com<mailto:notifications@github.com>> wrote:


@dominiklohmann<https://github.com/dominiklohmann> my ~/.skhdrc is literally just

:: command

cmd - o ; command
command < cmd - o ; default

command < cmd - h : chunkc tiling::window --focus west ; skhd --key 'cmd - o'
command < cmd - j : chunkc tiling::window --focus south ; skhd --key 'cmd - o'
command < cmd - k : chunkc tiling::window --focus north ; skhd --key 'cmd - o'
command < cmd - l : chunkc tiling::window --focus east ; skhd --key 'cmd - o'


But after pressing cmd - o all the cmd -h etc. key binds are just sent like normal through to the app I'm in

**Comment by theonlygusti** [comment] 2019-05-21 12:59
This isn't working for me in kitty (terminal), Discord.app, Mail.app

I didn't test in others yet

**Comment by koekeishiya** [comment] 2019-05-21 13:10
Try to run skhd manually from the command line with logging enabled: skhd -V

Sent from my iPhone

On 21 May 2019, at 14:59, George <notifications@github.com<mailto:notifications@github.com>> wrote:


This isn't working for me in kitty (terminal), Discord.app, Mail.app

I didn't test in others yet

**Comment by theonlygusti** [comment] 2019-05-21 13:34
@koekeishiya `skhd: could not lock pid-file! abort..`

Beforehand I'd been starting it with `brew services start skhd` and it was working generally (just not with the modes as I tried to do here^^)

skhd is not running right now, I ran `brew services stop skhd` but it said it wasn't running, and `sudo killall skhd` says no matching processes, and `ps -ax | grep skhd` shows nothing.

**Comment by koekeishiya** [comment] 2019-05-21 14:59
Stop brew services first, then `rm /tmp/skhd_$USER.pid` and `skhd -V`

**Comment by theonlygusti** [comment] 2019-05-21 15:08
@koekeishiya  `rm: /tmp/skhd_George.pid: No such file or directory`

and still `skhd: could not lock pid-file! abort..`

**Comment by theonlygusti** [comment] 2019-05-21 15:11
I just did `rm: /tmp/skhd.pid` and now it works

**Comment by koekeishiya** [comment] 2019-05-21 15:42
This was likely caused by a bug: #83. I've done a new release v0.3.4 which fixes this.

Basically, I'd forgotten that file locks initiated through the *flock* call persist through *fork*, thus if you execute a command that runs a persistent application, and then *skhd* is restarted for whatever reason - it will no longer be able to grab its lockfile.

**Comment by koekeishiya** [comment] 2019-05-21 15:45
The snippet posted by @dominiklohmann earlier should do what you want just fine. Closing this.

**Closed by koekeishiya** 2019-05-21 15:45 UTC
